[project]
name = "echoforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.35.0",
    "groq>=0.29.0",
    "python-dotenv>=1.1.1",
]
